---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - est.mitre.org
  resources:
  - estclusterissuers
  - estissuers
  - estorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - est.mitre.org
  resources:
  - estclusterissuers/finalizers
  - estissuers/finalizers
  - estorders/finalizers
  verbs:
  - update
- apiGroups:
  - est.mitre.org
  resources:
  - estclusterissuers/status
  - estissuers/status
  - estorders/status
  verbs:
  - get
  - patch
  - update
