#+TITLE: Certificate Manager Enrollment Over Secure Transport
* About
~est-operator~ is a [[https://cert-manager.io/][cert-manager]] [[https://cert-manager.io/docs/configuration/external/][External certificate issuer]] that implements a subset of [[https://tools.ietf.org/html/rfc7030][RFC 7030 Enrollment over Secure Transport]] (EST).  It provides custom resources for EST services and a custom controller that reconciles certificate requests.

~est-operator~ is written in Python using the [[https://kopf.readthedocs.io/en/stable/][kopf framework]].

This operator covers only a portion of RFC 7030; see [[docs/RFC7030.org][this document]] for an overview of what's implemented, planned, and not planned.

See [[docs/DESIGN.org][this document]] for an overview of this operator's design.
* Getting Started
** Prerequisites
- Kubernetes v1.19.1 or later.  ~est-operator~ should run on v1.16 or later, but is only tested with v1.19.1.
- Python 3.9 and packages.  [[./requirements.txt][requirements.txt]] has all Python package dependencies.  Install prerequistest with =pip=.
  #+BEGIN_SRC shell :results silent
pip install -r requirements.txt
  #+END_SRC
  [[./dev-requirements.txt][dev-requirements.txt]] has additional Python packages for development purposes (e.g., building packages). The full set of reqiurements can be installed with =pip=. The order of requirements files is important; =dev-requirements.txt= depends on =requirement.txt=.
  #+BEGIN_SRC shell :result silent
pip install -r requirements.txt -r dev-requirements.txt
  #+END_SRC
  This repository uses [[https://github.com/jazzband/pip-tools][pip-tools]] to build requirements files.
** Building
** Installing
See [[*Deployment]], below.  Also see [[docs/DESIGN.org][the design document]] for a deployment description. 
* Testing
** Style
** Component
** End-to-end
* Deployment
** In cluster
TBD.
** Out of cluster
The operator can be run "out of cluster," meaning in a process that runs outside of Kubernetes control.  This is useful for development, testing, and debugging ~est-operator~.  This mode is not recommended for production.

The ~kopf~ command will use the current cluster context in ~KUBECONFIG~ by default.
#+BEGIN_SRC shell :results silent
kopf run est-operator.py
#+END_SRC

See [[https://kopf.readthedocs.io/en/stable/][kopf documentation]] for more details of running in this mode.
* Federal Information Processing Standards (FIPS) 140-2 certified mode
The operator can be run "out of cluster" in FIPS mode by setting ~OPENSSL_FIPS=1~ in the shell environment before running ~kopf~.  This will require Python compiled with OpenSSL with the FIPS validated engine installed.

[[Dockerfile.fips][Dockerfile.fips]] builds a version of the operator image that maintains [[https://csrc.nist.gov/publications/detail/fips/140/2/final][FIPS 140-2]] certification.  The image is built on Amazon Linux 2 and has [[https://aws.amazon.com/blogs/publicsector/enabling-fips-mode-amazon-linux-2/][FIPS validated libraries installed according to AWS documentation.]]  The image runs with the environment variable ~OPENSSL_FIPS=1~ set, and startup code in [[estoperator/__init__.py][module initialization]] enables FIPS mode in the cryptographic library.

#+BEGIN_SRC bash :results silent :exports code
docker build -t est-operator:fips -f Dockerfile.fips .
#+END_SRC

FIPS 140-2 certification is only valid on AWS EC2 instances running Amazon Linux 2.  However, any platform with Python dynamically linked to OpenSSL /and/ has a validated module installed can also demonstrate certification.  Consult the [[https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&ModuleName=OpenSSL&CertificateStatus=Active&ValidationYear=0][NIST Cryptographic Module Validation Program list of OpenSSL modules]] for combinations of OpenSSL and platform that are certified.

* Built with
- Python 3.9
- [[https://github.com/nolar/kopf][kopf framework]]
- Docker
* Contibuting
TBD
* Versioning
TBD
* Authors
- Timothy J. Miller - /initial work/ - [[https://github.com/Cerebus][Cerebus]]
* License
[[./LICENSE][Apache License v2.0]]
* Acknowledgements
- [[https://www.mitre.org][The MITRE Corporation]] for allowing this work to be open sourced.
- [[https://cert-manager.io][Jetstack and all the cert-manager contributors]] for the framework that makes this extension possible.
- [[https://github.com/nolar][Sergey Vasilyev]] for kopf, so I don't have to learn Go yet.
