#+TITLE: Certificate Manager Enrollment Over Secure Transport
* About
~estissuer~ is a [[https://cert-manager.io/][cert-manager]] [[https://cert-manager.io/docs/configuration/external/][External certificate issuer]] that implements a subset of [[https://tools.ietf.org/html/rfc7030][RFC 7030 Enrollment over Secure Transport]] (EST).  It provides custom resources for EST services and a custom controller that reconciles certificate requests.

~est-operator~ is written in Python using the [[https://kopf.readthedocs.io/en/stable/][kopf framework]] and [[https://lightkube.readthedocs.io/en/latest/][lightkube]].

This operator covers only a portion of RFC 7030; see [[file:docs/RFC7030.org][this document]] for an overview of what's implemented, planned, and not planned.

See [[file:docs/DESIGN.org][this file]] for an overview of this operator's design.
* Getting Started
** Prerequisites
** Building
** Installing
See [[*Deployment]], below.  Also see [[file:docs/DESIGN.org][the design document]] for a deployment description.
* Testing
** Style
** Component
** End-to-end
* Deployment
** In cluster
TBD.
** Out of cluster
* Usage
- EstIssuer and EstClusterIssuer secrets must be passwords and labeled "est.mitre.org/registration=true".
- Certificate secrets must be labeled "est.mitre.org/certificate=true".
  - RFC 7030 renewals require mTLS authentication even when initial renewal uses a password regitration credential, so this label allows the controller to track certificate private keys.

* Federal Information Processing Standards (FIPS) 140-2 certified mode
This controller can be built to satisfy FIPS 140-2 certification requirements.  FIPS 140-2 certification depends on the module and the platform.  A platform with Python dynamically linked to OpenSSL /and/ links OpenSSL to a validated version of the OpenSSL FIPS Object Module can demonstrate FIPS 140-2 certification.  Consult the [[https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search?SearchMode=Basic&ModuleName=OpenSSL&CertificateStatus=Active&ValidationYear=0][NIST Cryptographic Module Validation Program list of OpenSSL modules]] for combinations of OpenSSL and platform that are certified.

*Note*: OpenSSL 1.0.2 is no longer supported by the OpenSSL project, but OpenSSL FIPS Object Module 2.0 is not compatible with OpenSSL 1.1.  A new version is [[https://www.openssl.org/blog/blog/2018/09/25/fips/][not available nor certified yet.]]

Other FIPS certified modules are available (e.g., GnuTLS and Network Security Services) but the work to integrate these modules is extensive.  We welcome merge requests on this topic.

** Building a FIPS version

** Building a FIPS container image

** Running a FIPS version out of cluster

* Built with

* Contibuting
TBD
* Versioning
TBD
* Authors
- Timothy J. Miller - /initial work/ - [[https://github.com/Cerebus][Cerebus]]
* License
[[./LICENSE][Apache License v2.0]]
* Acknowledgements
- [[https://www.mitre.org][The MITRE Corporation]] for allowing this work to be open sourced.
- [[https://cert-manager.io][Jetstack and all the cert-manager contributors]] for the framework that makes this extension possible.
- [[https://github.com/nolar][Sergey Vasilyev]] for kopf, so I don't have to learn Go yet.
