---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: estorders.est.mitre.org
spec:
  group: est.mitre.org
  names:
    kind: EstOrder
    listKind: EstOrderList
    plural: estorders
    singular: estorder
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EstOrders is the Schema for the estissuers API
        properties:
          apiVersion:
            description: >-
              APIVersion defines the versioned schema of this representation of
              an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: >-
              Kind is a string value representing the REST resource this object
              represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: >-
              EstOrders track requests over the RFC 7030 lifecycle. EstOrders
              are owned by CertificateRequest resources and are not created by
              end users.
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              issuerRef:
                description: >-
                  EstIssuer that will handle the request, and will be copied
                  from the owning CertificateRequest.
                type: object
                properties:
                  name:
                    description: >-
                      Name of the EstIssuer
                    type: string
                  kind:
                    description: >-
                      Should be EstIssuer or EstClusterIssuer
                    type: string
                    enum:
                      - "EstIssuer"
                      - "EstClusterIssuer"
                  group:
                    type: string
                    pattern: "est.mitre.org"
                required:
                  - name
                  - kind
                  - group
              request:
                description: >-
                  Certificate Signing Request copied from CertificateRequest.
                type: string
                pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
              renewal:
                type: boolean
                default: false
            required:
              - issuerRef
              - request
          status:
            description: Status defines the observed state of EstOrder
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
